* what linguistic features might be influencing the classifier's decisions:  
transcript의 kband접목 - 인기가 많은 talk일 수록 kband가 낮을것이다.

* Why?  
Umm......

* How to define _popular_ talk?  
`comments` column. view보다 level of engagement가 높으니까.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib as plt
import re
import nltk
import pickle

In [2]:
ted_main = pd.read_csv("../data/ted_main.csv")
tran = pd.read_csv("../data/transcripts.csv")

In [3]:
# remove NAs
ted_main.dropna(inplace=True)
tran.dropna(inplace=True)

In [4]:
ted_main.head()

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869

In [5]:
# sorting the TED talk original 
ted = ted_main[ted_main['event'].str.fullmatch(r'TED\d\d\d\d')]
ted.event.unique()

array(['TED2006', 'TED2004', 'TED2005', 'TED2003', 'TED2007', 'TED2002',
       'TED2008', 'TED1984', 'TED1990', 'TED1998', 'TED2001', 'TED2009',
       'TED2010', 'TED2011', 'TED1994', 'TED2012', 'TED2013', 'TED2014',
       'TED2015', 'TED2016', 'TED2017'], dtype=object)

In [6]:
# combine two files
ted = pd.merge(ted_main, tran, on = 'url')
ted.head()

,comments,description,duration,event,film_date,languages,main_speaker,name,num_speaker,published_date,ratings,related_talks,speaker_occupation,tags,title,url,views,transcript
0,4553,Sir Ken Robinson makes an entertaining and pro...,1164,TED2006,1140825600,60,Ken Robinson,Ken Robinson: Do schools kill creativity?,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 19645}, {...","[{'id': 865, 'hero': 'https://pe.tedcdn.com/im...",Author/educator,"['children', 'creativity', 'culture', 'dance',...",Do schools kill creativity?,https://www.ted.com/talks/ken_robinson_says_sc...,47227110,Good morning. How are you?(Laughter)It's been ...
1,265,With the same humor and humanity he exuded in ...,977,TED2006,1140825600,43,Al Gore,Al Gore: Averting the climate crisis,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 544}, {'i...","[{'id': 243, 'hero': 'https://pe.tedcdn.com/im...",Climate advocate,"['alternative energy', 'cars', 'climate change...",Averting the climate crisis,https://www.ted.com/talks/al_gore_on_averting_...,3200520,"Thank you so much, Chris. And it's truly a gre..."
2,124,New York Times columnist David Pogue takes aim...,1286,TED2006,1140739200,26,David Pogue,David Pogue: Simplicity sells,1,1151367060,"[{'id': 7, 'name': 'Funny', 'count': 964}, {'i...","[{'id': 1725, 'hero': 'https://pe.tedcdn.com/i...",Technology columnist,"['computers', 'entertainment', 'interface desi...",Simplicity sells,https://www.ted.com/talks/david_pogue_says_sim...,1636292,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,200,"In an emotionally charged talk, MacArthur-winn...",1116,TED2006,1140912000,35,Majora Carter,Majora Carter: Greening the ghetto,1,1151367060,"[{'id': 3, 'name': 'Courageous', 'count': 760}...","[{'id': 1041, 'hero': 'https://pe.tedcdn.com/i...",Activist for environmental justice,"['MacArthur grant', 'activism', 'business', 'c...",Greening the ghetto,https://www.ted.com/talks/majora_carter_s_tale...,1697550,If you're here today — and I'm very happy that...
4,593,You've never seen data presented like this. Wi...,1190,TED2006,1140566400,48,Hans Rosling,Hans Rosling: The best stats you've ever seen,1,1151440680,"[{'id': 9, 'name': 'Ingenious', 'count': 3202}...","[{'id': 2056, 'hero': 'https://pe.tedcdn.com/i...",Global health expert; data visionary,"['Africa', 'Asia', 'Google', 'demo', 'economic...",The best stats you've ever seen,https://www.ted.com/talks/hans_rosling_shows_t...,12005869,"About 10 years ago, I took on the task to teac..."

In [7]:
# select the columns I need
ted_clean = ted[['title', 'event', 'comments', 'transcript']]
ted_clean.head()

,title,event,comments,transcript
0,Do schools kill creativity?,TED2006,4553,Good morning. How are you?(Laughter)It's been ...
1,Averting the climate crisis,TED2006,265,"Thank you so much, Chris. And it's truly a gre..."
2,Simplicity sells,TED2006,124,"(Music: ""The Sound of Silence,"" Simon & Garfun..."
3,Greening the ghetto,TED2006,200,If you're here today — and I'm very happy that...
4,The best stats you've ever seen,TED2006,593,"About 10 years ago, I took on the task to teac..."

In [8]:
ted_clean.describe()

          comments
count  2461.000000
mean    192.722471
std     285.141388
min       2.000000
25%      63.000000
50%     117.000000
75%     223.000000
max    6404.000000

In [15]:
# tokenize the transcript
ted_clean['token'] = ted_clean.transcript.map(nltk.word_tokenize)

C:\Users\82102\AppData\Local\Temp\ipykernel_8552\210160556.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ted_clean['token'] = ted_clean.transcript.map(nltk.word_tokenize)

In [22]:
ted_clean

,title,event,comments,transcript,token
0,Do schools kill creativity?,TED2006,4553,Good morning. How are you?(Laughter)It's been ...,"[Good, morning, ., How, are, you, ?, (, Laught..."
1,Averting the climate crisis,TED2006,265,"Thank you so much, Chris. And it's truly a gre...","[Thank, you, so, much, ,, Chris, ., And, it, '..."
2,Simplicity sells,TED2006,124,"(Music: ""The Sound of Silence,"" Simon & Garfun...","[(, Music, :, ``, The, Sound, of, Silence, ,, ..."
3,Greening the ghetto,TED2006,200,If you're here today — and I'm very happy that...,"[If, you, 're, here, today, —, and, I, 'm, ver..."
4,The best stats you've ever seen,TED2006,593,"About 10 years ago, I took on the task to teac...","[About, 10, years, ago, ,, I, took, on, the, t..."
...,...,...,...,...,...
2456,What we're missing in the debate about immigra...,TED2017,17,"So, Ma was trying to explain something to me a...","[So, ,, Ma, was, trying, to, explain, somethin..."
2457,The most Martian place on Earth,TED2017,6,This is a picture of a sunset on Mars taken by...,"[This, is, a, picture, of, a, sunset, on, Mars..."
2458,What intelligent machines can learn from a sch...,TED2017,10,"In my early days as a graduate student, I went...","[In, my, early, days, as, a, graduate, student..."
2459,A black man goes undercover in the alt-right,TEDxMileHigh,32,I took a cell phone and accidentally made myse...,"[I, took, a, cell, phone, and, accidentally, m..."
2460,How a video game might help us build better ci...,TED2017,8,"We humans are becoming an urban species, so ci...","[We, humans, are, becoming, an, urban, species..."

**Kband 다시 만들어야함..**

In [19]:
f = open('C://Users//82102//Desktop//program//2022 fall//LING 2231//goog_kband.pkl', 'rb')
kband = pickle.load(f)
f.close()

In [24]:
for i in ted_clean['token']:
    for j in i:
        kband[j]

20000

In [30]:
count = 0
for i in ted_clean['token'][0]:
    if i.isalnum():
        count += kband[i.lower()]
print(count)

KeyError: 'curiously'

In [33]:
kband['bloke']

KeyError: 'bloke'

In [27]:
type(ted_clean['token'][0][0])

str